### ISSUE TITLE
Valtion 1.5.0 compile error, with NextJS all latest versions

### ISSUE THREAD

**Issue by sivadinesh1** [pmndrs/valtio#412]
Version 1.4.0 works well. upgrading to Valtio 1.5.0 causes compilation errors.

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/../node_modules/use-sync-external-store/shim' is not supported resolving ES modules imported from /Users/sivadinesh/Documents/products/2022/greenpot/node_modules/valtio/esm/index.mjs
Did you mean to import use-sync-external-store/shim/index.js?
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:414:17)
    at moduleResolve (node:internal/modules/esm/resolve:983:10)
    at defaultResolve (node:internal/modules/esm/resolve:1080:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: '/node_modules/use-sync-external-store/shim'

**Comment by dai-shi** [comment]
Can you try #411?
https://ci.codesandbox.io/status/pmndrs/valtio/pr/411
Please find "Local Install Instructions" in ☝️ .

**Comment by sivadinesh1** [comment]
> Can you try #411? https://ci.codesandbox.io/status/pmndrs/valtio/pr/411 Please find "Local Install Instructions" in ☝️ .

Create new compile errors.
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
    at Object.useSyncExternalStore (/Users/sivadinesh/Documents/products/2022/greenpot/node_modules/react-dom/cjs/react-dom-server.browser.development.js:5051:11)
    at useSyncExternalStore (/Users/sivadinesh/Documents/products/2022/greenpot/node_modules/react/cjs/react.development.js:1671:21)
    at useSnapshot (file:///Users/sivadinesh/Documents/products/2022/greenpot/node_modules/valtio/esm/index.mjs:19:24)

**Comment by dai-shi** [comment]
@sivadinesh1 Thanks for reporting it!
Now, it's a different error, which is related with https://github.com/pmndrs/zustand/issues/886.
I'll work on the fix. Would you please create a new issue to track it? Thanks.

**Comment by MD2990** [comment]
Same here

**Comment by dai-shi** [comment]
@MD2990 Thanks for reporting. You can open a new issue too.

**Comment by sivadinesh1** [comment]
created new issue #415
