### ISSUE TITLE
using valtio with skypack.dev

### ISSUE THREAD

**Issue by s-cork** [pmndrs/valtio#452]
Currently it fails to import:
```js
>>> var mod = await import("https://cdn.skypack.dev/valtio")

Uncaught SyntaxError: The requested module '/-/use-sync-external-store@v1.0.0-ZzO0qn27iKOvDc2m57IV/dist=es2019,mode=imports/unoptimized/shim/index.js' does not provide an export named 'useSyncExternalStore' (at valtio.js:4:9)
```

Similar problem with zustand:
```js
>>> var mod = await import("https://cdn.skypack.dev/zustand")

Uncaught SyntaxError: The requested module '/-/use-sync-external-store@v1.1.0-2zD0nsSlmd6FK3zepjJs/dist=es2019,mode=imports/unoptimized/shim/with-selector.js' does not provide an export named 'useSyncExternalStoreWithSelector' (at zustand.js:4:9)
```

Both errors are from the `use-sync-external-store` library
versions prior to the inclusion of this library built using skypack.dev

**Comment by dai-shi** [comment]
Hi, thanks for reporting.
I'm not sure if this is fixable on our end.
Hope someone has some suggestions.
