### ISSUE TITLE
The macro fix for vite added in #386 does not work

### ISSUE THREAD

**Issue by beaugunderson** [pmndrs/valtio#512]
Hi there, I'm trying to use the macro for `vite` using the instructions from the README.

I get this error when I run `yarn dev`:

```
yarn run v1.22.19
$ vite
failed to load config from /Users/beau/p/test/vite.config.ts
error when starting dev server:
file:///Users/beau/p/test/node_modules/valtio/esm/macro/vite.mjs:4
import { MacroError } from 'babel-plugin-macros';
         ^^^^^^^^^^
SyntaxError: Named export 'MacroError' not found. The requested module 'babel-plugin-macros' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'babel-plugin-macros';
const { MacroError } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async loadConfigFromBundledFile (file:///Users/beau/p/test/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62893:21)
    at async loadConfigFromFile (file:///Users/beau/p/test/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62780:28)
    at async resolveConfig (file:///Users/beau/p/test/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:62398:28)
    at async createServer (file:///Users/beau/p/test/node_modules/vite/dist/node/chunks/dep-71eb12cb.js:59018:20)
    at async CAC.<anonymous> (file:///Users/beau/p/test/node_modules/vite/dist/node/cli.js:699:24)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This seems to be an issue with mixing ESM (which vite converts everything to, if I understand correctly how it works) and CJS.

I'm using node v18.4.0 and the most recent vite, valtio, react, and typescript as of today.

Here's my `vite.config.js`:

```
import { defineConfig } from 'vite';
import macro from 'valtio/macro/vite';
import react from '@vitejs/plugin-react';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    macro,

    react({
      babel: {
        plugins: ['@emotion/babel-plugin'],
      },

      jsxImportSource: '@emotion/react',
    }),
  ],
});
```

**Comment by dai-shi** [comment]
@Aslemammad Can you take this?

**Comment by Aslemammad** [comment]
@beaugunderson Could you try checking the Codesandbox builds in #517?
