### ISSUE TITLE
Should `use-sync-external-store` be an optional dependency?

### ISSUE THREAD

**Issue by richardanaya** [pmndrs/valtio#591]
I was using valtio in a react application with vitejs and it kept saying react was required. Not sure what's up.

```
 yarn dev
yarn run v1.22.19
$ vite

  VITE v3.2.4  ready in 164 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
✘ [ERROR] Could not resolve "react"

    node_modules/use-sync-external-store/cjs/use-sync-external-store-shim.development.js:26:30:
      26 │           var React = require('react');
         ╵                               ~~~~~~~

  You can mark the path "react" as external to exclude it from the bundle, which
  will remove this error. You can also surround this "require" call with a
  try/catch block to handle this failure at run-time instead of bundle-time.

/Users/richardanaya/lit-valtio/node_modules/esbuild/lib/main.js:1566
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/use-sync-external-store/cjs/use-sync-external-store-shim.development.js:26:30: ERROR: Could not resolve "react"
    at failureErrorWithLog (/Users/richardanaya/lit-valtio/node_modules/esbuild/lib/main.js:1566:15)
    at /Users/richardanaya/lit-valtio/node_modules/esbuild/lib/main.js:1024:28
    at runOnEndCallbacks (/Users/richardanaya/lit-valtio/node_modules/esbuild/lib/main.js:1438:61)
    at buildResponseToResult (/Users/richardanaya/lit-valtio/node_modules/esbuild/lib/main.js:1022:7)
    at /Users/richardanaya/lit-valtio/node_modules/esbuild/lib/main.js:1134:14
    at responseCallbacks.<computed> (/Users/richardanaya/lit-valtio/node_modules/esbuild/lib/main.js:671:9)
    at handleIncomingPacket (/Users/richardanaya/lit-valtio/node_modules/esbuild/lib/main.js:726:9)
    at Socket.readFromStdout (/Users/richardanaya/lit-valtio/node_modules/esbuild/lib/main.js:647:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 30,
        file: 'node_modules/use-sync-external-store/cjs/use-sync-external-store-shim.development.js',
        length: 7,
        line: 26,
        lineText: "          var React = require('react');",
        namespace: '',
        suggestion: ''
      },
      notes: [
        {
          location: null,
          text: 'You can mark the path "react" as external to exclude it from the bundle, which will remove this error. You can also surround this "require" call with a try/catch block to handle this failure at run-time instead of bundle-time.'
        }
      ],
      pluginName: '',
      text: 'Could not resolve "react"'
    }
  ],
  warnings: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by dai-shi** [comment]
Hmm, can't reproduce it on my local machine.
Can you try with empty vite project?

**Comment by richardanaya** [comment]
What I do is

```
npm create vite@latest
```

make a project with `vanilla` + `typescript`. go into the folder.

```
npm install valtio
```

modify the `counter.ts` file

```typescript
// counter.ts
import { proxy } from "valtio";

const counter = proxy({count:0});

export function setupCounter(element: HTMLButtonElement) {
  const render = () => {
    element.innerHTML = `count is ${counter.count}`
  }
  element.addEventListener('click', () => {
    counter.count += 1;
    render()
  });
  render()
}
```

the repo is here I use https://github.com/richardanaya/valtio-typescript

**Comment by dai-shi** [comment]
This is what I did just now:
```bash
git clone https://github.com/richardanaya/valtio-typescript
cd valtio-typescript
npm i
npm run build
```

And, I see no errors:
```
> valtio-typescript@0.0.0 build
> tsc && vite build

vite v3.2.4 building for production...
✓ 21 modules transformed.
dist/assets/typescript.f6ead1af.svg   1.40 KiB
dist/index.html                       0.44 KiB
dist/assets/index.c9a26d18.js         3.95 KiB / gzip: 1.87 KiB
dist/assets/index.d5a34e39.css        1.19 KiB / gzip: 0.62 KiB
```

**Comment by dai-shi** [comment]
Now, I get this:
```
yarn run v1.22.19
$ tsc && vite build
vite v3.2.4 building for production...
transforming (1) index.html'react' is imported by react?commonjs-external, but could not be resolved – treating it as an external dependency
✓ 17 modules transformed.
'useRef' is not exported by __vite-optional-peer-dep:react:valtio, imported by node_modules/valtio/esm/index.mjs
```

Here's the fix:
```diff
diff --git a/src/counter.ts b/src/counter.ts
index 420bfa9..551aedf 100644
--- a/src/counter.ts
+++ b/src/counter.ts
@@ -1,4 +1,4 @@
-import { proxy } from "valtio";
+import { proxy } from "valtio/vanilla";
 
 const counter = proxy({count:0});
 
```

**Comment by richardanaya** [comment]
Thank you @dai-shi !
