### ISSUE TITLE
Uncaught TypeError: Cannot read properties of undefined (reading '4')

### ISSUE THREAD

**Issue by dxhuii** [pmndrs/valtio#603]
```js
import { devtools } from 'valtio/utils'

const state = proxy({ count: 0, text: 'hello' })
devtools(state, { name: 'state name', enabled: true })
```

react.development.js:1311 Uncaught TypeError: Cannot read properties of undefined (reading '4')
    at subscribe (vanilla.mjs:186:1)
    at devtools (utils.mjs:95:1)
    at ./src/store/edit.ts (edit.ts:560:27)
    at options.factory (react refresh:8:1)
    at __webpack_require__ (bootstrap:26:1)
    at fn (hot module replacement:63:1)
    at ./src/index.tsx (src_index_tsx.6f0aa10e.js:31:70)
    at options.factory (react refresh:8:1)
    at __webpack_require__ (bootstrap:26:1)
    at fn (hot module replacement:63:1)

**Comment by dai-shi** [comment]
Can you modify this to reproduce the error?

https://codesandbox.io/s/pensive-breeze-w1oiff?file=/src/App.js

**Comment by dxhuii** [comment]
> Can you modify this to reproduce the error?
> 
> https://codesandbox.io/s/pensive-breeze-w1oiff?file=/src/App.js

It's fine, it's a dependency package problem, after reinstallation it's fine.
